config/routes.rb
Rails.application.routes.draw do

  root 'websites#index'

  resources :websites
  resources :short_urls do
    get :info, on: :member
  end

end

app/models/click.rb
class Click < ActiveRecord::Base
  belongs_to :short_url
end

app/models/short_url.rb
class ShortUrl < ActiveRecord::Base
  has_many :clicks
end

app/models/website.rb
class Website < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/short_urls_controller.rb
class ShortUrlsController < ApplicationController

  def index
    @urls = ShortUrl.all
  end

  def show
    @url = ShortUrl.find(params[:id])
    @url.clicks.create(ip: request.remote_ip)
    redirect_to @url.url
  end

  def create
    @url = ShortUrl.new(url_params)
    @url.save
    redirect_to short_urls_path(@url)
  end

  def info
    @url = ShortUrl.find(params[:id])
  end

  private

    def url_params
      params.require(:short_url).permit(:url)
    end
end

app/controllers/websites_controller.rb
class WebsitesController < ApplicationController

  def index
    @order_by = params[:order] || 'rank'
    @websites = Website.order("#{@order_by} asc").page(params[:page]).per(25)
  end

  def show
    @website = Website.find(params[:id])
    render :json => @website
  end

  def update
    @website = Website.find(params[:id])
    @website.update_attributes(website_params)
    respond_to do |format|   
      format.html    
      format.js    
    end
  end

  private

    def website_params
      params.require(:website).permit(:url, :rank, :pageviews_per_user)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_modal.html.slim
.modal.fade#modal role="dialog" tabindex="-1" 
  .modal-dialog
    .modal-content
      .modal-header
        button.close aria-label="Close" data-dismiss="modal" type="button" 
          span aria-hidden="true"  &times;
        h4.modal-title Edit Website
      .modal-body
        = form_for :website, method: :patch, remote: true do |f|
          .form-group
            = f.label :rank
            = f.text_field :rank, class: 'form-control'
          .form-group
            = f.label :url
            = f.text_field :url, class: 'form-control'
          .form-group
            = f.label :pageviews_per_user
            = f.text_field :pageviews_per_user, class: 'form-control'
          = f.submit "Save", class: 'btn btn-success'

app/views/layouts/application.html.slim
doctype html
html
  head
    title Buzzstarter
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    = render 'layouts/modal'
    .container
      = yield

app/views/short_urls/index.html.slim
.row: .col-lg-12
  = form_for ShortUrl.new do |f|
    .form-group
      = f.label :url, placeholder: 'Enter destination url'
      = f.text_field :url, class: 'form-control'
    = f.submit "Save", class: 'btn btn-success'
  table.table.table-striped
    thead
      th short url
      th destination url
      th clicks
    tbody
      - @urls.each do |url|
        tr
          td=short_url_url(url)
          td=url.url
          td=link_to url.clicks.count, info_short_url_path(url)
      

app/views/short_urls/info.html.slim
.row: .col-lg-12
  table.table.table-striped
    thead
      th IP
    tbody
      - @url.clicks.each do |click|
        tr
          td=click.ip
      

app/views/websites/_website.html.slim
tr id="website-#{website.id}" data-id=website.id
  td= website.rank
  td= website.url
  td= website.pageviews_per_user

app/views/websites/index.html.slim
.row.websites: .col-lg-12
  table.table.table-striped
    thead
      th= link_to 'Rank', root_url(order: 'rank')
      th= link_to 'Website', root_url(order: 'url')
      th= link_to 'Pageviews per user', root_url(order: 'pageviews_per_user')
    tbody
      = render @websites
      
  = paginate @websites

app/views/websites/update.js.slim
|
  $('#modal').modal('hide')
  $("#website-#{@website.id}").replaceWith('#{escape_javascript(render @website)}')